### ISSUE TITLE
Translation error in Workflow2

### ISSUE THREAD

**Issue by PsychoOyster** [urakubo/UNI-EM#30]
In the english verison of  "Example workflow 2: Membrane segmentation using 3D Flood Filling Networks (FFN)"
In the "Training" section, it says :
"Check "Sparse Z" if the z-pitch (nm/pixel) of the EM image is **smaller** than the xy-pitch (nm/pixel)."
However in the Japanese version it says to check "Sparse Z" if the z-pitch is **greater** than the xy-pitch. We think the english version should be changed.

**Comment by urakubo** [comment]
Thank you kind comment! Updated. Please feel free to give any comments, bug reports, etc. I will revise them as well as possible.
