### ISSUE TITLE
Trained Weights of FFN

### ISSUE THREAD

**Issue by BoyuLyu** [urakubo/UNI-EM#42]
Could the trained weights of FFN (using SNEMI3D dataset) be shared? It is taking too long for training. 
Thanks!

**Comment by urakubo** [comment]
If you use tensorflow1.X, please use the following folder. This folder will be recognized as a "Model Folder".
https://www.dropbox.com/s/oxv4nqzfgyzx9q6/DNN_model_tensorflow.zip?dl=0
You can also find the similar.
https://github.com/google/ffn/tree/master/models/fib25

If you use tensorflow2.X, I am sorry but this model is invalid, and I have not made an example model using SNEMI3D dataset.

**Comment by BoyuLyu** [comment]
Thank you so much!
